# Generated by Django 3.0 on 2019-12-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcampaign',
            name='location',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='max_age',
            field=models.IntegerField(db_index=True, default=100),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='min_age',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('BLOCKED', 'BLOCKED'), ('ARCHIVED', 'ARCHIVED')], db_index=True, default='CREATED', max_length=32),
        ),
    ]
