# Generated by Django 3.0 on 2019-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_management', '0002_auto_20191217_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='preference',
            field=models.CharField(choices=[('category1', 'category1'), ('category2', 'category2'), ('category3', 'category3'), ('category4', 'category4'), ('category5', 'category5')], db_index=True, max_length=64),
        ),
    ]
